#!/usr/bin/env python3
"""
Extract all library books from ALFRED.7 for Alfred Pelrock ScummVM engine.

Book data format in ALFRED.7 (offset 0x309E0 to 0x33F05):
- Title:  55 bytes (space-padded, may contain 0xC8 line breaks)
- Author: 30 bytes (space-padded)
- Genre:  22 bytes (space-padded)
- Status: 1 byte (0x01 = available, 0x02 = on loan, 0x20 = special)

Total: 108 bytes per entry
Approximately 125-126 books
"""

import json
import sys

ALFRED7_PATH = 'files/ALFRED.7'
BOOK_DATA_START = 0x309E0
BOOK_DATA_END = 0x33F05

TITLE_SIZE = 55
AUTHOR_SIZE = 30
GENRE_SIZE = 20
SHELF_LETTER_SIZE = 1
SHELF_ROW_SIZE = 1
STATUS_SIZE = 1
ENTRY_SIZE = TITLE_SIZE + AUTHOR_SIZE + GENRE_SIZE + SHELF_LETTER_SIZE + SHELF_ROW_SIZE + STATUS_SIZE  # 108 bytes


def clean_string(data):
    """Convert bytes to string, handle special characters, strip padding."""
    # CP437 is the DOS code page
    text = data.decode('cp437', errors='replace')
    # Replace line break marker 0xC8 with space
    text = text.replace('\u2568', ' ').replace('╚', ' ')
    # Replace other special chars
    text = text.replace('\xad', '').replace('\xa4', 'n')  # soft hyphen, ñ
    # Strip trailing spaces
    text = text.rstrip()
    # Collapse multiple spaces
    while '  ' in text:
        text = text.replace('  ', ' ')
    return text


def parse_books(filepath):
    """Parse all books from ALFRED.7 file."""
    books = []

    with open(filepath, 'rb') as f:
        f.seek(BOOK_DATA_START)
        data = f.read(BOOK_DATA_END - BOOK_DATA_START)

    offset = 0
    book_num = 0

    while offset + ENTRY_SIZE <= len(data):
        title_raw = data[offset:offset + TITLE_SIZE]
        author_raw = data[offset + TITLE_SIZE:offset + TITLE_SIZE + AUTHOR_SIZE]
        genre_raw = data[offset + TITLE_SIZE + AUTHOR_SIZE:offset + TITLE_SIZE + AUTHOR_SIZE + GENRE_SIZE]
        shelf_letter = data[offset + 105]  # Shelf letter (A-Z or 0x20)
        shelf_row = data[offset + 106]     # Shelf row (1-3 or 0x20)
        status_byte = data[offset + 107]   # Status (0x01=available, 0x02=physical)

        title = clean_string(title_raw)
        author = clean_string(author_raw)
        genre = clean_string(genre_raw)

        # Skip empty entries
        if not title.strip():
            offset += ENTRY_SIZE
            continue

        # Convert shelf letter to char if valid
        shelf_char = chr(shelf_letter) if shelf_letter >= ord('A') and shelf_letter <= ord('Z') else ' '
        shelf_row_num = shelf_row if shelf_row >= 1 and shelf_row <= 3 else 0

        # Determine availability from status byte
        # 0x01 = Catalog only (Disponible - no physical copy)
        # 0x02 = Physical book on shelf (may be borrowed - Prestado)
        # For gameplay, status 0x02 means the book CAN be memorized/found on shelf
        has_physical_copy = (status_byte == 0x02)

        book_num += 1
        books.append({
            'index': book_num,
            'title': title,
            'author': author,
            'genre': genre,
            'shelf_letter': shelf_char,
            'shelf_row': shelf_row_num,
            'status_byte': status_byte,
            'has_physical_copy': has_physical_copy,
            'offset': hex(BOOK_DATA_START + offset)
        })

        offset += ENTRY_SIZE

    return books


def generate_cpp_header(books, output_path):
    """Generate C++ header file with book data."""

    lines = []
    lines.append('/* ScummVM - Graphic Adventure Engine')
    lines.append(' *')
    lines.append(' * Alfred Pelrock Library Book Database')
    lines.append(' * Extracted from ALFRED.7 offset 0x309E0 to 0x33F05')
    lines.append(' *')
    lines.append(' * This file was auto-generated by extract_alfred7_books_full.py')
    lines.append(' * DO NOT EDIT MANUALLY')
    lines.append(' *')
    lines.append(' * Book format in ALFRED.7 (108 bytes per entry):')
    lines.append(' *   - Title:        55 bytes (space-padded)')
    lines.append(' *   - Author:       30 bytes (space-padded)')
    lines.append(' *   - Genre:        20 bytes (space-padded)')
    lines.append(' *   - Shelf Letter:  1 byte (A-Z or space if catalog-only)')
    lines.append(' *   - Shelf Row:     1 byte (1-3 or space)')
    lines.append(' *   - Status:        1 byte (0x01=catalog only, 0x02=physical copy)')
    lines.append(' */')
    lines.append('')
    lines.append('#ifndef PELROCK_LIBRARY_BOOKS_H')
    lines.append('#define PELROCK_LIBRARY_BOOKS_H')
    lines.append('')
    lines.append('#include "common/scummsys.h"')
    lines.append('')
    lines.append('namespace Pelrock {')
    lines.append('')
    lines.append('// Book data location in ALFRED.7')
    lines.append('static const uint32 kBookDataOffset = 0x309E0;')
    lines.append('static const uint32 kBookDataEnd = 0x33F05;')
    lines.append('static const int kBookEntrySize = 108;  // 55 + 30 + 20 + 1 + 1 + 1')
    lines.append('')
    lines.append('// Field sizes')
    lines.append('static const int kBookTitleSize = 55;')
    lines.append('static const int kBookAuthorSize = 30;')
    lines.append('static const int kBookGenreSize = 20;')
    lines.append('')
    lines.append('// Status byte values')
    lines.append('static const byte kBookStatusCatalogOnly = 0x01;  // No physical copy')
    lines.append('static const byte kBookStatusPhysical = 0x02;     // Has physical copy on shelf')
    lines.append('')
    lines.append('struct LibraryBook {')
    lines.append('    const char *title;')
    lines.append('    const char *author;')
    lines.append('    const char *genre;')
    lines.append('    char shelfLetter;    // A-Z for shelf location, space if catalog-only')
    lines.append('    byte shelfRow;       // 1-3 for row number, 0 if catalog-only')
    lines.append('    bool hasPhysicalCopy;  // true = can be found on shelf, false = catalog only')
    lines.append('};')
    lines.append('')
    lines.append('static const int kLibraryBookCount = %d;' % len(books))
    lines.append('')
    lines.append('static const LibraryBook kLibraryBooks[] = {')

    for i, book in enumerate(books):
        # Escape quotes and backslashes in strings
        title = book['title'].replace('\\', '\\\\').replace('"', '\\"')
        author = book['author'].replace('\\', '\\\\').replace('"', '\\"')
        genre = book['genre'].replace('\\', '\\\\').replace('"', '\\"')
        shelf_letter = book['shelf_letter'] if book['shelf_letter'] != ' ' else ' '
        shelf_row = book['shelf_row']
        has_physical = 'true' if book['has_physical_copy'] else 'false'

        if len(title) > 40:
            lines.append('    // Book %d: %s...' % (i+1, title[:40]))
        else:
            lines.append('    // Book %d: %s' % (i+1, title))
        lines.append('    {"%s", "%s", "%s", \'%s\', %d, %s},' % (title, author, genre, shelf_letter, shelf_row, has_physical))

    lines.append('};')
    lines.append('')
    lines.append('} // namespace Pelrock')
    lines.append('')
    lines.append('#endif // PELROCK_LIBRARY_BOOKS_H')

    with open(output_path, 'w', encoding='utf-8') as f:
        f.write('\n'.join(lines))

    print("Generated %s with %d books" % (output_path, len(books)))


def main():
    books = parse_books(ALFRED7_PATH)

    print("Found %d books in ALFRED.7" % len(books))
    print()

    # Count by type
    physical_count = sum(1 for b in books if b['has_physical_copy'])
    catalog_only_count = len(books) - physical_count
    print("Physical copies (can find on shelf): %d" % physical_count)
    print("Catalog only (no physical copy):     %d" % catalog_only_count)
    print()

    # Show first 20 books
    print("First 20 books:")
    print("-" * 110)
    for book in books[:20]:
        status = "Physical" if book['has_physical_copy'] else "Catalog"
        shelf = "%s%d" % (book['shelf_letter'], book['shelf_row']) if book['has_physical_copy'] else "N/A"
        print("%3d. %-42s | %-18s | %-12s | %s | %s" % (
            book['index'], book['title'][:42], book['author'][:18],
            book['genre'][:12], shelf, status))
    print()

    # Show last 10 books
    print("Last 10 books:")
    print("-" * 110)
    for book in books[-10:]:
        status = "Physical" if book['has_physical_copy'] else "Catalog"
        shelf = "%s%d" % (book['shelf_letter'], book['shelf_row']) if book['has_physical_copy'] else "N/A"
        print("%3d. %-42s | %-18s | %-12s | %s | %s" % (
            book['index'], book['title'][:42], book['author'][:18],
            book['genre'][:12], shelf, status))
    print()

    # Generate C++ header
    generate_cpp_header(books, 'library_books_full.h')

    # Also output JSON for reference
    with open('library_books.json', 'w', encoding='utf-8') as f:
        json.dump(books, f, indent=2, ensure_ascii=False)
    print("Generated library_books.json")


if __name__ == '__main__':
    main()
